---
- name: Configuração base do ambiente NETOPS
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ac_organization: NETOPS
    ac_inv_netops: INV-NETOPS

    netops_hosts:
      rtr1dc1:
        groups: [cisco, dc1]
        vars:
          ansible_host: 3.142.54.192
          private_ip: 172.16.92.125
      rtr2dc1:
        groups: [arista, dc1]
        vars:
          ansible_host: 18.191.154.37
          private_ip: 172.18.252.223
      rtr4dc1:
        groups: [arista, dc1]
        vars:
          ansible_host: 3.135.187.207
          private_ip: 172.18.87.178
      rtr2dc2:
        groups: [arista, dc1]
        vars:
          ansible_host: 3.17.157.91
          private_ip: 172.18.117.41
      rtr3dc1:
        groups: [juniper, dc1]
        vars:
          ansible_host: 18.216.125.168
          private_ip: 172.16.190.27
      rtr3dc2:
        groups: [juniper, dc1]
        vars:
          ansible_host: 18.119.29.169
          private_ip: 172.16.133.152
      rtr1dc2:
        groups: [cisco, dc2]
        vars:
          ansible_host: 3.144.45.6
          private_ip: 172.16.3.140
      rtr1dc3:
        groups: [cisco, dc2]
        vars:
          ansible_host: 3.144.11.102
          private_ip: 172.16.49.114
      rtr1dc4:
        groups: [cisco, dc2]
        vars:
          ansible_host: 3.145.125.190
          private_ip: 172.16.174.40
      rtr4dc2:
        groups: [arista, dc2]
        vars:
          ansible_host: 18.117.145.31
          private_ip: 172.18.117.15
      rtr2dc3:
        groups: [arista, dc2]
        vars:
          ansible_host: 3.145.59.51
          private_ip: 172.18.50.122
      rtr4dc3:
        groups: [arista, dc2]
        vars:
          ansible_host: 3.142.136.201
          private_ip: 172.18.109.229
      rtr2dc4:
        groups: [arista, dc2]
        vars:
          ansible_host: 18.219.229.10
          private_ip: 172.18.165.199
      rtr4dc4:
        groups: [arista, dc2]
        vars:
          ansible_host: 3.137.182.89
          private_ip: 172.18.162.230
      rtr3dc3:
        groups: [juniper, dc2]
        vars:
          ansible_host: 3.145.16.31
          private_ip: 172.16.134.128
      rtr3dc4:
        groups: [juniper, dc2]
        vars:
          ansible_host: 18.223.241.112
          private_ip: 172.16.97.87

  tasks:
    - name: Garantir que a organização existe
      ansible.controller.organization:
        name: "{{ ac_organization }}"
        state: present

    - name: Criar inventário NETOPS
      ansible.controller.inventory:
        name: "{{ ac_inv_netops }}"
        description: "Inventário de dispositivos de rede"
        organization: "{{ ac_organization }}"
        state: present

    - name: Criar grupos base
      ansible.controller.group:
        name: "{{ item }}"
        inventory: "{{ ac_inv_netops }}"
        state: present
      loop:
        - cisco
        - arista
        - juniper
        - dc1
        - dc2

    - name: Criar hosts com variáveis
      ansible.controller.host:
        name: "{{ item.key }}"
        inventory: "{{ ac_inv_netops }}"
        enabled: true
        variables: "{{ item.value.vars }}"
      loop: "{{ lookup('dict', netops_hosts) }}"

    - name: Associar hosts aos grupos
      ansible.controller.group:
        name: "{{ group }}"
        inventory: "{{ ac_inv_netops }}"
        hosts:
          - "{{ item.key }}"
        preserve_existing_hosts: true
      loop: "{{ lookup('dict', netops_hosts) | subelements('value.groups') }}"
      loop_control:
        label: "{{ item.0.key }} -> {{ item.1 }}"
      vars:
        group: "{{ item.1 }}"
