---
- name: Inventários INV-DC1-NETOPS, INV-DC2-NETOPS e INV-NET (simples e funcional)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ac_organization: NETOPS

    # Variáveis por grupo (iguais em todos inventários)
    group_vars:
      cisco:
        ansible_network_os: ios
        ansible_connection: network_cli
      arista:
        ansible_network_os: eos
        ansible_connection: network_cli
        ansible_become: true
        ansible_become_method: enable
      juniper:
        ansible_network_os: junos
        ansible_connection: netconf
      dc1: {}
      dc2: {}

    ######################################################################
    # DC1  -> nomes rtr1..rtr4
    ######################################################################
    dc1_hosts_new:
      rtr1: { ansible_host: 3.142.54.192, private_ip: 172.16.92.125,  vendor: cisco   }
      rtr2: { ansible_host: 18.191.154.37, private_ip: 172.18.252.223, vendor: arista  }
      rtr3: { ansible_host: 18.216.125.168, private_ip: 172.16.190.27, vendor: juniper }
      rtr4: { ansible_host: 3.135.187.207, private_ip: 172.18.87.178,  vendor: arista  }

    dc1_all:    [rtr1, rtr2, rtr3, rtr4]
    dc1_cisco:  [rtr1]
    dc1_arista: [rtr2, rtr4]
    dc1_juniper: [rtr3]

    ######################################################################
    # DC2  -> nomes rtr1..rtr8  (apenas DC2 + DC3, sem DC4)
    ######################################################################
    # mapeamento: rtr1..rtr4 = (dc2), rtr5..rtr8 = (dc3)
    dc2_hosts_new:
      rtr1: { ansible_host: 3.144.45.6,   private_ip: 172.16.3.140,   vendor: cisco   }    # rtr1dc2
      rtr2: { ansible_host: 3.17.157.91,  private_ip: 172.18.117.41,  vendor: arista  }    # rtr2dc2
      rtr3: { ansible_host: 18.119.29.169,private_ip: 172.16.133.152, vendor: juniper }    # rtr3dc2
      rtr4: { ansible_host: 18.117.145.31,private_ip: 172.18.117.15,  vendor: arista  }    # rtr4dc2
      rtr5: { ansible_host: 3.144.11.102, private_ip: 172.16.49.114,  vendor: cisco   }    # rtr1dc3
      rtr6: { ansible_host: 3.145.59.51,  private_ip: 172.18.50.122,  vendor: arista  }    # rtr2dc3
      rtr7: { ansible_host: 3.145.16.31,  private_ip: 172.16.134.128, vendor: juniper }    # rtr3dc3
      rtr8: { ansible_host: 3.142.136.201,private_ip: 172.18.109.229, vendor: arista  }    # rtr4dc3

    dc2_all:    [rtr1, rtr2, rtr3, rtr4, rtr5, rtr6, rtr7, rtr8]
    dc2_cisco:  [rtr1, rtr5]
    dc2_arista: [rtr2, rtr4, rtr6, rtr8]
    dc2_juniper: [rtr3, rtr7]

    ######################################################################
    # INV-NET (consolidado) -> nomes únicos: dc1-rtrX / dc2-rtrY
    ######################################################################
    net_hosts:
      dc1-rtr1: { ansible_host: 3.142.54.192,  private_ip: 172.16.92.125,  vendor: cisco   }
      dc1-rtr2: { ansible_host: 18.191.154.37, private_ip: 172.18.252.223, vendor: arista  }
      dc1-rtr3: { ansible_host: 18.216.125.168,private_ip: 172.16.190.27,  vendor: juniper }
      dc1-rtr4: { ansible_host: 3.135.187.207, private_ip: 172.18.87.178,  vendor: arista  }

      dc2-rtr1: { ansible_host: 3.144.45.6,   private_ip: 172.16.3.140,   vendor: cisco   }
      dc2-rtr2: { ansible_host: 3.17.157.91,  private_ip: 172.18.117.41,  vendor: arista  }
      dc2-rtr3: { ansible_host: 18.119.29.169,private_ip: 172.16.133.152, vendor: juniper }
      dc2-rtr4: { ansible_host: 18.117.145.31,private_ip: 172.18.117.15,  vendor: arista  }
      dc2-rtr5: { ansible_host: 3.144.11.102, private_ip: 172.16.49.114,  vendor: cisco   }
      dc2-rtr6: { ansible_host: 3.145.59.51,  private_ip: 172.18.50.122,  vendor: arista  }
      dc2-rtr7: { ansible_host: 3.145.16.31,  private_ip: 172.16.134.128, vendor: juniper }
      dc2-rtr8: { ansible_host: 3.142.136.201,private_ip: 172.18.109.229, vendor: arista  }

    net_dc1:    [dc1-rtr1, dc1-rtr2, dc1-rtr3, dc1-rtr4]
    net_dc2:    [dc2-rtr1, dc2-rtr2, dc2-rtr3, dc2-rtr4, dc2-rtr5, dc2-rtr6, dc2-rtr7, dc2-rtr8]
    net_cisco:  [dc1-rtr1, dc2-rtr1, dc2-rtr5]
    net_arista: [dc1-rtr2, dc1-rtr4, dc2-rtr2, dc2-rtr4, dc2-rtr6, dc2-rtr8]
    net_juniper: [dc1-rtr3, dc2-rtr3, dc2-rtr7]

  tasks:
    ######################################################################
    # INV-DC1-NETOPS
    ######################################################################
    - name: Criar inventário INV-DC1-NETOPS
      ansible.controller.inventory:
        name: INV-DC1-NETOPS
        description: Datacenter 1
        organization: "{{ ac_organization }}"
        state: present

    - name: Criar grupos (INV-DC1-NETOPS)
      ansible.controller.group:
        name: "{{ item }}"
        inventory: INV-DC1-NETOPS
        state: present
        variables: "{{ group_vars[item] }}"
      loop: ['cisco','arista','juniper','dc1']

    - name: Criar hosts DC1 (rtr1..rtr4)
      ansible.controller.host:
        name: "{{ item.key }}"
        inventory: INV-DC1-NETOPS
        enabled: true
        variables:
          ansible_host: "{{ item.value.ansible_host }}"
          private_ip:  "{{ item.value.private_ip }}"
      loop: "{{ dc1_hosts_new | dict2items }}"

    - name: Adicionar DC1 -> grupo dc1
      ansible.controller.group:
        name: dc1
        inventory: INV-DC1-NETOPS
        hosts: "{{ dc1_all }}"
        preserve_existing_hosts: true

    - name: Adicionar DC1 -> grupo cisco
      ansible.controller.group:
        name: cisco
        inventory: INV-DC1-NETOPS
        hosts: "{{ dc1_cisco }}"
        preserve_existing_hosts: true

    - name: Adicionar DC1 -> grupo arista
      ansible.controller.group:
        name: arista
        inventory: INV-DC1-NETOPS
        hosts: "{{ dc1_arista }}"
        preserve_existing_hosts: true

    - name: Adicionar DC1 -> grupo juniper
      ansible.controller.group:
        name: juniper
        inventory: INV-DC1-NETOPS
        hosts: "{{ dc1_juniper }}"
        preserve_existing_hosts: true

    ######################################################################
    # INV-DC2-NETOPS
    ######################################################################
    - name: Criar inventário INV-DC2-NETOPS
      ansible.controller.inventory:
        name: INV-DC2-NETOPS
        description: Datacenter 2
        organization: "{{ ac_organization }}"
        state: present

    - name: Criar grupos (INV-DC2-NETOPS)
      ansible.controller.group:
        name: "{{ item }}"
        inventory: INV-DC2-NETOPS
        state: present
        variables: "{{ group_vars[item] }}"
      loop: ['cisco','arista','juniper','dc2']

    - name: Criar hosts DC2 (rtr1..rtr8)
      ansible.controller.host:
        name: "{{ item.key }}"
        inventory: INV-DC2-NETOPS
        enabled: true
        variables:
          ansible_host: "{{ item.value.ansible_host }}"
          private_ip:  "{{ item.value.private_ip }}"
      loop: "{{ dc2_hosts_new | dict2items }}"

    - name: Adicionar DC2 -> grupo dc2
      ansible.controller.group:
        name: dc2
        inventory: INV-DC2-NETOPS
        hosts: "{{ dc2_all }}"
        preserve_existing_hosts: true

    - name: Adicionar DC2 -> grupo cisco
      ansible.controller.group:
        name: cisco
        inventory: INV-DC2-NETOPS
        hosts: "{{ dc2_cisco }}"
        preserve_existing_hosts: true

    - name: Adicionar DC2 -> grupo arista
      ansible.controller.group:
        name: arista
        inventory: INV-DC2-NETOPS
        hosts: "{{ dc2_arista }}"
        preserve_existing_hosts: true

    - name: Adicionar DC2 -> grupo juniper
      ansible.controller.group:
        name: juniper
        inventory: INV-DC2-NETOPS
        hosts: "{{ dc2_juniper }}"
        preserve_existing_hosts: true

    ######################################################################
    # INV-NET (Consolidado)
    ######################################################################
    - name: Criar inventário INV-NET (todos os hosts)
      ansible.controller.inventory:
        name: INV-NET
        description: Inventário consolidado (DC1 + DC2)
        organization: "{{ ac_organization }}"
        state: present

    - name: Criar grupos (INV-NET)
      ansible.controller.group:
        name: "{{ item }}"
        inventory: INV-NET
        state: present
        variables: "{{ group_vars[item] }}"
      loop: ['cisco','arista','juniper','dc1','dc2']

    - name: Criar hosts INV-NET (dc1-rtrX / dc2-rtrY)
      ansible.controller.host:
        name: "{{ item.key }}"
        inventory: INV-NET
        enabled: true
        variables:
          ansible_host: "{{ item.value.ansible_host }}"
          private_ip:  "{{ item.value.private_ip }}"
      loop: "{{ net_hosts | dict2items }}"

    - name: INV-NET -> grupo dc1
      ansible.controller.group:
        name: dc1
        inventory: INV-NET
        hosts: "{{ net_dc1 }}"
        preserve_existing_hosts: true

    - name: INV-NET -> grupo dc2
      ansible.controller.group:
        name: dc2
        inventory: INV-NET
        hosts: "{{ net_dc2 }}"
        preserve_existing_hosts: true

    - name: INV-NET -> grupo cisco
      ansible.controller.group:
        name: cisco
        inventory: INV-NET
        hosts: "{{ net_cisco }}"
        preserve_existing_hosts: true

    - name: INV-NET -> grupo arista
      ansible.controller.group:
        name: arista
        inventory: INV-NET
        hosts: "{{ net_arista }}"
        preserve_existing_hosts: true

    - name: INV-NET -> grupo juniper
      ansible.controller.group:
        name: juniper
        inventory: INV-NET
        hosts: "{{ net_juniper }}"
        preserve_existing_hosts: true
