=---
- name: Configuração dos inventários NV-DC1-NETOPS e NV-DC2-NETOPS
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ac_organization: SEC

    # Hosts filtrados por DC
    dc1_hosts:
      rtr1dc1:
        groups: [cisco, dc1]
        vars:
          ansible_host: 3.142.54.192
          private_ip: 172.16.92.125
      rtr2dc1:
        groups: [arista, dc1]
        vars:
          ansible_host: 18.191.154.37
          private_ip: 172.18.252.223
      rtr4dc1:
        groups: [arista, dc1]
        vars:
          ansible_host: 3.135.187.207
          private_ip: 172.18.87.178
      rtr2dc2:
        groups: [arista, dc1]
        vars:
          ansible_host: 3.17.157.91
          private_ip: 172.18.117.41
      rtr3dc1:
        groups: [juniper, dc1]
        vars:
          ansible_host: 18.216.125.168
          private_ip: 172.16.190.27
      rtr3dc2:
        groups: [juniper, dc1]
        vars:
          ansible_host: 18.119.29.169
          private_ip: 172.16.133.152

    dc2_hosts:
      rtr1dc2:
        groups: [cisco, dc2]
        vars:
          ansible_host: 3.144.45.6
          private_ip: 172.16.3.140
      rtr1dc3:
        groups: [cisco, dc2]
        vars:
          ansible_host: 3.144.11.102
          private_ip: 172.16.49.114
      rtr1dc4:
        groups: [cisco, dc2]
        vars:
          ansible_host: 3.145.125.190
          private_ip: 172.16.174.40
      rtr4dc2:
        groups: [arista, dc2]
        vars:
          ansible_host: 18.117.145.31
          private_ip: 172.18.117.15
      rtr2dc3:
        groups: [arista, dc2]
        vars:
          ansible_host: 3.145.59.51
          private_ip: 172.18.50.122
      rtr4dc3:
        groups: [arista, dc2]
        vars:
          ansible_host: 3.142.136.201
          private_ip: 172.18.109.229
      rtr2dc4:
        groups: [arista, dc2]
        vars:
          ansible_host: 18.219.229.10
          private_ip: 172.18.165.199
      rtr4dc4:
        groups: [arista, dc2]
        vars:
          ansible_host: 3.137.182.89
          private_ip: 172.18.162.230
      rtr3dc3:
        groups: [juniper, dc2]
        vars:
          ansible_host: 3.145.16.31
          private_ip: 172.16.134.128
      rtr3dc4:
        groups: [juniper, dc2]
        vars:
          ansible_host: 18.223.241.112
          private_ip: 172.16.97.87

    # Variáveis por grupo
    netops_groups:
      cisco:
        ansible_network_os: ios
        ansible_connection: network_cli
      arista:
        ansible_network_os: eos
        ansible_connection: network_cli
        ansible_become: true
        ansible_become_method: enable
      juniper:
        ansible_network_os: junos
        ansible_connection: netconf
      dc1: {}
      dc2: {}

  tasks:
    - name: Garantir que a organização existe
      ansible.controller.organization:
        name: "{{ ac_organization }}"
        state: present

#######################
# INVENTÁRIO DC1
#######################
    - name: Criar inventário NV-DC1-NETOPS
      ansible.controller.inventory:
        name: NV-DC1-NETOPS
        description: "Inventário apenas do Datacenter 1"
        organization: "{{ ac_organization }}"
        state: present

    - name: Criar grupos base em NV-DC1-NETOPS
      ansible.controller.group:
        name: "{{ item.key }}"
        inventory: NV-DC1-NETOPS
        state: present
        variables: "{{ item.value }}"
      loop: "{{ lookup('dict', netops_groups) }}"

    - name: Criar hosts DC1 com variáveis
      ansible.controller.host:
        name: "{{ item.key }}"
        inventory: NV-DC1-NETOPS
        enabled: true
        variables: "{{ item.value.vars }}"
      loop: "{{ lookup('dict', dc1_hosts) }}"

    - name: Associar hosts DC1 aos grupos
      ansible.controller.group:
        name: "{{ item.1 }}"
        inventory: NV-DC1-NETOPS
        hosts:
          - "{{ item.0.key }}"
        preserve_existing_hosts: true
      loop: "{{ lookup('dict', dc1_hosts) | subelements('value.groups') }}"
      loop_control:
        label: "{{ item.0.key }} -> {{ item.1 }}"

#######################
# INVENTÁRIO DC2
#######################
    - name: Criar inventário NV-DC2-NETOPS
      ansible.controller.inventory:
        name: NV-DC2-NETOPS
        description: "Inventário apenas do Datacenter 2"
        organization: "{{ ac_organization }}"
        state: present

    - name: Criar grupos base em NV-DC2-NETOPS
      ansible.controller.group:
        name: "{{ item.key }}"
        inventory: NV-DC2-NETOPS
        state: present
        variables: "{{ item.value }}"
      loop: "{{ lookup('dict', netops_groups) }}"

    - name: Criar hosts DC2 com variáveis
      ansible.controller.host:
        name: "{{ item.key }}"
        inventory: NV-DC2-NETOPS
        enabled: true
        variables: "{{ item.value.vars }}"
      loop: "{{ lookup('dict', dc2_hosts) }}"

    - name: Associar hosts DC2 aos grupos
      ansible.controller.group:
        name: "{{ item.1 }}"
        inventory: NV-DC2-NETOPS
        hosts:
          - "{{ item.0.key }}"
        preserve_existing_hosts: true
      loop: "{{ lookup('dict', dc2_hosts) | subelements('value.groups') }}"
      loop_control:
        label: "{{ item.0.key }} -> {{ item.1 }}"
