---
- name: Cisco facts + debug (read-only)
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Coletar facts (IOS)
      cisco.ios.ios_facts:
      register: f

    - name: Exibir infos básicas
      debug:
        msg:
          - "Device:   {{ inventory_hostname }}"
          - "Hostname: {{ f.ansible_facts.ansible_net_hostname | default('N/D') }}"
          - "Modelo:   {{ f.ansible_facts.ansible_net_model    | default('N/D') }}"
          - "Versão:   {{ f.ansible_facts.ansible_net_version  | default('N/D') }}"
          - "Serial:   {{ f.ansible_facts.ansible_net_serialnum| default('N/D') }}"
