---
- name: Configure VLANs
  hosts: arista
  gather_facts: false

  tasks:

    - name: Use vlans resource module
      arista.eos.eos_vlans:
        state: deleted
        config:
          - name: desktops
            vlan_id: 20
          - name: servers
            vlan_id: 30
          - name: printers
            vlan_id: 40
#          - name: DMZ
#            vlan_id: 50

    - name: Show VLAN config after changes
      arista.eos.eos_command:
        commands:
          - "show running-config | section vlan"
      register: vlan_output

    - name: Print VLAN config
      debug:
        var: vlan_output.stdout_lines