---
- name: Auditoria de Inventário de Rede
  hosts: "{{ target_group | default('all') }}"
  gather_facts: no
  tasks:

    - name: Cisco IOS facts
      ios_facts:
      register: ios_out
      when: ansible_network_os == "ios"

    - name: Mostrar infos Cisco
      debug:
        msg:
          - "Hostname: {{ ios_out.ansible_facts.ansible_net_hostname }}"
          - "Modelo:   {{ ios_out.ansible_facts.ansible_net_model }}"
          - "Versão:   {{ ios_out.ansible_facts.ansible_net_version }}"
          - "Serial:   {{ ios_out.ansible_facts.ansible_net_serialnum }}"
      when: ios_out is defined

    - name: Arista EOS facts
      eos_facts:
      register: eos_out
      when: ansible_network_os == "eos"

    - name: Mostrar infos Arista
      debug:
        msg:
          - "Hostname: {{ eos_out.ansible_facts.ansible_net_hostname }}"
          - "Modelo:   {{ eos_out.ansible_facts.ansible_net_model }}"
          - "Versão:   {{ eos_out.ansible_facts.ansible_net_version }}"
          - "Serial:   {{ eos_out.ansible_facts.ansible_net_serialnum }}"
      when: eos_out is defined

    - name: Juniper Junos facts
      junos_facts:
      register: junos_out
      when: ansible_network_os == "junos"

    - name: Mostrar infos Juniper
      debug:
        msg:
          - "Hostname: {{ junos_out.ansible_facts.ansible_net_hostname }}"
          - "Modelo:   {{ junos_out.ansible_facts.ansible_net_model }}"
          - "Versão:   {{ junos_out.ansible_facts.ansible_net_version }}"
          - "Serial:   {{ junos_out.ansible_facts.ansible_net_serialnum }}"
      when: junos_out is defined
