---
- name: Coleta de facts Cisco/Arista/Juniper
  hosts: routers
  gather_facts: no

  tasks:
    - name: Cisco IOS facts
      cisco.ios.ios_facts:
      register: f
      when: ansible_network_os == "ios"

    - name: Arista EOS facts
      arista.eos.eos_facts:
      register: f
      when: ansible_network_os == "eos"

    - name: Juniper Junos facts
      junipernetworks.junos.junos_facts:
      register: f
      when: ansible_network_os == "junos"

    - name: Mostrar informações básicas
      debug:
        msg:
          - "Device:   {{ inventory_hostname }}"
          - "Hostname: {{ f.ansible_facts.ansible_net_hostname | default('N/D') }}"
          - "Modelo:   {{ f.ansible_facts.ansible_net_model    | default('N/D') }}"
          - "Versão:   {{ f.ansible_facts.ansible_net_version  | default('N/D') }}"
          - "Serial:   {{ f.ansible_facts.ansible_net_serialnum| default('N/D') }}"
      when: f is defined
