---
- name: Auditoria de Inventário de Rede (IOS/EOS/JUNOS)
  hosts: "{{ target_group | default('all') }}"
  gather_facts: no

  vars:
    ssh_common_args: >-
      -o PreferredAuthentications=password,keyboard-interactive
      -o PubkeyAuthentication=no

  tasks:
    - name: Forçar autenticação por senha
      set_fact:
        ansible_ssh_common_args: "{{ ssh_common_args }}"
      when: ansible_connection in ['network_cli', 'netconf']

    - name: Inicializar variável de saída
      set_fact:
        vendor_out: {}

    # ===== Cisco IOS =====
    - block:
        - name: Coletar facts (IOS)
          ios_facts:
          register: vendor_out
      when: ansible_network_os == 'ios'
      rescue:
        - name: Marcar coleta IOS como vazia
          set_fact:
            vendor_out: {}

    # ===== Arista EOS =====
    - block:
        - name: Coletar facts (EOS)
          eos_facts:
          register: vendor_out
      when: ansible_network_os == 'eos'
      rescue:
        - name: Marcar coleta EOS como vazia
          set_fact:
            vendor_out: {}

    # ===== Juniper JUNOS =====
    - block:
        - name: Coletar facts (JUNOS)
          junos_facts:
          register: vendor_out
      when: ansible_network_os == 'junos'
      rescue:
        - name: Marcar coleta JUNOS como vazia
          set_fact:
            vendor_out: {}

    - name: Normalizar inventário
      set_fact:
        inv_norm:
          device:   "{{ inventory_hostname }}"
          os:       "{{ ansible_network_os | default('N/D') }}"
          hostname: "{{ (vendor_out.ansible_facts | default({})).ansible_net_hostname | default('N/D') }}"
          model:    "{{ (vendor_out.ansible_facts | default({})).ansible_net_model    | default('N/D') }}"
          version:  "{{ (vendor_out.ansible_facts | default({})).ansible_net_version  | default('N/D') }}"
          serial:   "{{ (vendor_out.ansible_facts | default({})).ansible_net_serialnum| default('N/D') }}"

    - name: Exibir inventário normalizado
      debug:
        msg:
          - "Device:   {{ inv_norm.device }}"
          - "OS:       {{ inv_norm.os }}"
          - "Hostname: {{ inv_norm.hostname }}"
          - "Modelo:   {{ inv_norm.model }}"
          - "Versão:   {{ inv_norm.version }}"
          - "Serial:   {{ inv_norm.serial }}"
